import type { FileRow } from './first-batch-fixture';

export const rows: Record<number, FileRow[]> = {
  '1': [
    {
      key: '1',
      name: 'Semi Design design draft.fig',
      nameIconSrc: '/demos/table/figma-icon.png',
      size: '2M',
      owner: 'Jiang Pengzhi',
      updateTime: '2020-02-02 05:13',
      avatarBg: 'grey',
    },
    {
      key: '2',
      name: 'Semi Design share docs',
      nameIconSrc: '/demos/table/docs-icon.png',
      size: '2M',
      owner: 'Hao Xuan',
      updateTime: '2020-01-17 05:31',
      avatarBg: 'red',
    },
    {
      key: '3',
      name: 'Design docs',
      nameIconSrc: '/demos/table/docs-icon.png',
      size: '34KB',
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
  ],
  '2': [
    {
      key: '1',
      name: 'Semi Design design draft.fig',
      nameIconSrc: '/demos/table/figma-icon.png',
      size: '2M',
      owner: 'Jiang Pengzhi',
      updateTime: '2020-02-02 05:13',
      avatarBg: 'grey',
    },
    {
      key: '2',
      name: 'Semi Design share docs',
      nameIconSrc: '/demos/table/docs-icon.png',
      size: '2M',
      owner: 'Hao Xuan',
      updateTime: '2020-01-17 05:31',
      avatarBg: 'red',
    },
    {
      key: '3',
      name: 'Design docs',
      nameIconSrc: '/demos/table/docs-icon.png',
      size: '34KB',
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
  ],
  '3': [
    {
      key: '1',
      name: 'Semi Design design draft.fig',
      nameIconSrc: '/demos/table/figma-icon.png',
      size: '2M',
      owner: 'Jiang Pengzhi',
      updateTime: '2020-02-02 05:13',
      avatarBg: 'grey',
    },
    {
      key: '2',
      name: 'Semi Design share docs',
      nameIconSrc: '/demos/table/docs-icon.png',
      size: '2M',
      owner: 'Hao Xuan',
      updateTime: '2020-01-17 05:31',
      avatarBg: 'red',
    },
    {
      key: '3',
      name: 'Design docs',
      nameIconSrc: '/demos/table/docs-icon.png',
      size: '34KB',
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
    {
      key: '4',
      name: 'Semi D2C design draft.fig',
      nameIconSrc: '/demos/table/figma-icon.png',
      size: '2M',
      owner: 'Jiang Pengzhi',
      updateTime: '2020-02-02 05:13',
      avatarBg: 'grey',
    },
    {
      key: '5',
      name: 'Semi D2C share docs',
      nameIconSrc: '/demos/table/docs-icon.png',
      size: '2M',
      owner: 'Hao Xuan',
      updateTime: '2020-01-17 05:31',
      avatarBg: 'red',
    },
    {
      key: '6',
      name: 'Semi D2C Design docs',
      nameIconSrc: '/demos/table/docs-icon.png',
      size: '34KB',
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
  ],
  '4': [
    {
      key: '1',
      name: 'Semi Design design draft title may be a bit long Tooltip should be displayed at this time.fig',
      nameIconSrc: '/demos/table/figma-icon.png',
      size: '2M',
      owner: 'Jiang Pengzhi',
      updateTime: '2020-02-02 05:13',
      avatarBg: 'grey',
    },
    {
      key: '2',
      name: 'Semi Design share docs',
      nameIconSrc: '/demos/table/docs-icon.png',
      size: '2M',
      owner: 'Hao Xuan',
      updateTime: '2020-01-17 05:31',
      avatarBg: 'red',
    },
    {
      key: '3',
      name: 'Design docs',
      nameIconSrc: '/demos/table/docs-icon.png',
      size: '34KB',
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
    {
      key: '4',
      name: 'Semi D2C design draft title may be a bit long Tooltip should be displayed at this time.fig',
      nameIconSrc: '/demos/table/docs-icon.png',
      size: '34KB',
      owner: 'Jiang Qi',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'green',
    },
  ],
  '9': [
    {
      key: '1',
      name: 'Semi Design draft.fig',
      nameIconSrc: '/demos/table/figma-icon.png',
      size: 3,
      owner: 'Jiang',
      updateTime: '2020-02-02 05:13',
      avatarBg: 'grey',
    },
    {
      key: '2',
      name: 'Semi D2C draft',
      nameIconSrc: '/demos/table/docs-icon.png',
      owner: 'Hao',
      updateTime: '2020-01-17 05:31',
      avatarBg: 'red',
    },
    {
      key: '3',
      name: 'Semi D2C doc 3',
      nameIconSrc: '/demos/table/docs-icon.png',
      size: 1,
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
    {
      key: '4',
      name: 'Semi Design doc 4',
      nameIconSrc: '/demos/table/docs-icon.png',
      size: 5,
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
    {
      key: '5',
      name: 'Semi D2C doc 5',
      nameIconSrc: '/demos/table/docs-icon.png',
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
    {
      key: '6',
      name: 'Semi Design doc 6',
      nameIconSrc: '/demos/table/docs-icon.png',
      size: 2,
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
  ],
  '14': [
    {
      key: '1',
      name: 'Semi Design design draft.fig',
      nameIconSrc: '/demos/table/figma-icon.png',
      size: '2M',
      owner: 'Jiang Pengzhi',
      updateTime: '2020-02-02 05:13',
      avatarBg: 'grey',
    },
    {
      key: '2',
      name: 'Semi Design share docs',
      nameIconSrc: '/demos/table/docs-icon.png',
      size: '2M',
      owner: 'Hao Xuan',
      updateTime: '2020-01-17 05:31',
      avatarBg: 'red',
    },
    {
      key: '3',
      name: 'Design docs',
      nameIconSrc: '/demos/table/docs-icon.png',
      size: '34KB',
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
  ],
  '15': [
    {
      key: '1',
      name: 'Semi Design design draft.fig',
      nameIconSrc: '/demos/table/figma-icon.png',
      size: '2M',
      owner: 'Jiang Pengzhi',
      updateTime: '2020-02-02 05:13',
      avatarBg: 'grey',
    },
    {
      key: '2',
      name: 'Semi Design share docs',
      nameIconSrc: '/demos/table/docs-icon.png',
      size: '2M',
      owner: 'Hao Xuan',
      updateTime: '2020-01-17 05:31',
      avatarBg: 'red',
    },
    {
      key: '3',
      name: 'Design docs',
      nameIconSrc: '/demos/table/docs-icon.png',
      size: '34KB',
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
  ],
};
