// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_bn_IN } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_bn_IN as Readonly<SemiLocale>;

export default locale;
