// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_ca } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_ca as Readonly<SemiLocale>;

export default locale;
