// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_ceb_PH } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_ceb_PH as Readonly<SemiLocale>;

export default locale;
