// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_cs_CZ } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_cs_CZ as Readonly<SemiLocale>;

export default locale;
