// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_el_GR } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_el_GR as Readonly<SemiLocale>;

export default locale;
