// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_en_GB } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_en_GB as Readonly<SemiLocale>;

export default locale;
