// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_en_US } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_en_US as Readonly<SemiLocale>;

export default locale;
