// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_es } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_es as Readonly<SemiLocale>;

export default locale;
