// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_es_419 } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_es_419 as Readonly<SemiLocale>;

export default locale;
