// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_fi_FI } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_fi_FI as Readonly<SemiLocale>;

export default locale;
