// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_fr_CA } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_fr_CA as Readonly<SemiLocale>;

export default locale;
