// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_he_IL } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_he_IL as Readonly<SemiLocale>;

export default locale;
