// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_hu_HU } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_hu_HU as Readonly<SemiLocale>;

export default locale;
