// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_ja_JP } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_ja_JP as Readonly<SemiLocale>;

export default locale;
