// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_jv_ID } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_jv_ID as Readonly<SemiLocale>;

export default locale;
