// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_km_KH } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_km_KH as Readonly<SemiLocale>;

export default locale;
