// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_ko_KR } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_ko_KR as Readonly<SemiLocale>;

export default locale;
