// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_nb } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_nb as Readonly<SemiLocale>;

export default locale;
