// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_nl_NL } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_nl_NL as Readonly<SemiLocale>;

export default locale;
