// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_pl_PL } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_pl_PL as Readonly<SemiLocale>;

export default locale;
