// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_pt } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_pt as Readonly<SemiLocale>;

export default locale;
