// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_ru_RU } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_ru_RU as Readonly<SemiLocale>;

export default locale;
