// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_sv_SE } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_sv_SE as Readonly<SemiLocale>;

export default locale;
