// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_th_TH } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_th_TH as Readonly<SemiLocale>;

export default locale;
