// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_tr_TR } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_tr_TR as Readonly<SemiLocale>;

export default locale;
