// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_uk_UA } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_uk_UA as Readonly<SemiLocale>;

export default locale;
