// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_vi_VN } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_vi_VN as Readonly<SemiLocale>;

export default locale;
