// Generated by scripts/generate-locales.mjs; do not edit by hand.
import { pinnedLocale_zh_TW } from '@workspace/foundation-integration';

import type { SemiLocale } from '../../config-provider';

const locale = pinnedLocale_zh_TW as Readonly<SemiLocale>;

export default locale;
