import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const workspaceRoot = fileURLToPath(new URL('..', import.meta.url));
const vendorSourceRoot = path.join(
  workspaceRoot,
  'vendor/semi-design/packages/semi-ui/locale/source',
);
const integrationRoot = path.join(workspaceRoot, 'packages/foundation-integration/src');
const publicSourceRoot = path.join(workspaceRoot, 'packages/ui/src/locale/source');
const inventoryPath = path.join(workspaceRoot, 'docs/inventory/semi-v2.102.0.json');
const checkOnly = process.argv.includes('--check');

function exportName(sourceName) {
  return `pinnedLocale_${sourceName}`;
}

async function expectedFiles() {
  const sourceNames = (await readdir(vendorSourceRoot))
    .filter((fileName) => fileName.endsWith('.ts'))
    .map((fileName) => fileName.slice(0, -3))
    .sort();
  const inventory = JSON.parse(await readFile(inventoryPath, 'utf8'));
  const inventoryNames = [...inventory.assets.locales].sort();

  if (sourceNames.length !== 57 || JSON.stringify(sourceNames) !== JSON.stringify(inventoryNames)) {
    throw new Error(
      `固定 Locale 清单与 inventory 不一致：vendor=${sourceNames.length}, inventory=${inventoryNames.length}`,
    );
  }

  const integrationJs = [
    '// Generated by scripts/generate-locales.mjs from the read-only v2.102.0 submodule.',
    '// Locale content stays in vendor; the public build selects and inlines these re-exports.',
    ...sourceNames.flatMap((sourceName) => [
      '// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.',
      `export { default as ${exportName(sourceName)} } from '../../../vendor/semi-design/packages/semi-ui/locale/source/${sourceName}.ts';`,
    ]),
    '',
  ].join('\n');
  const integrationDts = [
    '// Generated by scripts/generate-locales.mjs.',
    ...sourceNames.map(
      (sourceName) => `export const ${exportName(sourceName)}: Readonly<Record<string, unknown>>;`,
    ),
    '',
  ].join('\n');
  const publicFiles = Object.fromEntries(
    sourceNames.map((sourceName) => [
      path.join(publicSourceRoot, `${sourceName}.ts`),
      [
        '// Generated by scripts/generate-locales.mjs; do not edit by hand.',
        `import { ${exportName(sourceName)} } from '@workspace/foundation-integration';`,
        '',
        `import type { SemiLocale } from '../../config-provider';`,
        '',
        `const locale = ${exportName(sourceName)} as Readonly<SemiLocale>;`,
        '',
        'export default locale;',
        '',
      ].join('\n'),
    ]),
  );

  return {
    sourceNames,
    files: {
      [path.join(integrationRoot, 'locale.js')]: integrationJs,
      [path.join(integrationRoot, 'locale.d.ts')]: integrationDts,
      ...publicFiles,
    },
  };
}

async function currentSourceFiles() {
  try {
    return (await readdir(publicSourceRoot))
      .filter((fileName) => fileName.endsWith('.ts'))
      .map((fileName) => path.join(publicSourceRoot, fileName));
  } catch {
    return [];
  }
}

const { files, sourceNames } = await expectedFiles();
const expectedPaths = new Set(Object.keys(files));
const unexpectedPaths = (await currentSourceFiles()).filter(
  (filePath) => !expectedPaths.has(filePath),
);
const drift = [];

for (const [filePath, expected] of Object.entries(files)) {
  let actual;
  try {
    actual = await readFile(filePath, 'utf8');
  } catch {
    actual = undefined;
  }
  if (actual !== expected) drift.push(path.relative(workspaceRoot, filePath));
}
drift.push(...unexpectedPaths.map((filePath) => path.relative(workspaceRoot, filePath)));

if (checkOnly) {
  if (drift.length > 0) {
    throw new Error(`Locale 生成产物漂移：${drift.join(', ')}`);
  }
  process.stdout.write(`Locale 生成产物通过：${sourceNames.length} 个固定语言源\n`);
} else {
  await mkdir(publicSourceRoot, { recursive: true });
  for (const [filePath, content] of Object.entries(files)) {
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, content);
  }
  if (unexpectedPaths.length > 0) {
    throw new Error(`Locale 目录存在非生成 TypeScript 文件：${unexpectedPaths.join(', ')}`);
  }
  process.stdout.write(`已生成 ${sourceNames.length} 个固定 Locale facade\n`);
}
