import type { FileRow } from './first-batch-fixture';

export const rows: Record<number, FileRow[]> = {
  '1': [
    {
      key: '1',
      name: 'Semi Design 设计稿.fig',
      nameIconSrc: '/demos/table-figma-icon.png',
      size: '2M',
      owner: '姜鹏志',
      status: 'success',
      updateTime: '2020-02-02 05:13',
      avatarBg: 'grey',
    },
    {
      key: '2',
      name: 'Semi Design 分享演示文稿',
      nameIconSrc: '/demos/table-docs-icon.png',
      size: '2M',
      owner: '郝宣',
      status: 'pending',
      updateTime: '2020-01-17 05:31',
      avatarBg: 'red',
    },
    {
      key: '3',
      name: '设计文档',
      nameIconSrc: '/demos/table-docs-icon.png',
      size: '34KB',
      status: 'wait',
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
  ],
  '2': [
    {
      key: '1',
      name: 'Semi Design 设计稿.fig',
      nameIconSrc: '/demos/table-figma-icon.png',
      size: '2M',
      owner: '姜鹏志',
      status: 'success',
      updateTime: '2020-02-02 05:13',
      avatarBg: 'grey',
    },
    {
      key: '2',
      name: 'Semi Design 分享演示文稿',
      nameIconSrc: '/demos/table-docs-icon.png',
      size: '2M',
      owner: '郝宣',
      status: 'pending',
      updateTime: '2020-01-17 05:31',
      avatarBg: 'red',
    },
    {
      key: '3',
      name: '设计文档',
      nameIconSrc: '/demos/table-docs-icon.png',
      size: '34KB',
      status: 'wait',
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
  ],
  '3': [
    {
      key: '1',
      name: 'Semi Design 设计稿.fig',
      nameIconSrc: '/demos/table-figma-icon.png',
      size: '2M',
      owner: '姜鹏志',
      status: 'success',
      updateTime: '2020-02-02 05:13',
      avatarBg: 'grey',
    },
    {
      key: '2',
      name: 'Semi Design 分享演示文稿',
      nameIconSrc: '/demos/table-docs-icon.png',
      size: '2M',
      owner: '郝宣',
      status: 'pending',
      updateTime: '2020-01-17 05:31',
      avatarBg: 'red',
    },
    {
      key: '3',
      name: '设计文档',
      nameIconSrc: '/demos/table-docs-icon.png',
      size: '34KB',
      status: 'wait',
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
    {
      key: '4',
      name: 'Semi D2C 设计稿.fig',
      nameIconSrc: '/demos/table-figma-icon.png',
      size: '2M',
      owner: '姜鹏志',
      status: 'wait',
      updateTime: '2020-02-02 05:13',
      avatarBg: 'grey',
    },
    {
      key: '5',
      name: 'Semi D2C 分享演示文稿',
      nameIconSrc: '/demos/table-docs-icon.png',
      size: '2M',
      owner: '郝宣',
      status: 'pending',
      updateTime: '2020-01-17 05:31',
      avatarBg: 'red',
    },
    {
      key: '6',
      name: 'Semi D2C 设计文档',
      nameIconSrc: '/demos/table-docs-icon.png',
      size: '34KB',
      status: 'success',
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
  ],
  '4': [
    {
      key: '1',
      name: 'Semi Design 设计稿标题可能有点长这时候应该显示 Tooltip.fig',
      nameIconSrc: '/demos/table-figma-icon.png',
      size: '2M',
      owner: '姜鹏志',
      status: 'success',
      updateTime: '2020-02-02 05:13',
      avatarBg: 'grey',
    },
    {
      key: '2',
      name: 'Semi Design 分享演示文稿',
      nameIconSrc: '/demos/table-docs-icon.png',
      size: '2M',
      owner: '郝宣',
      status: 'pending',
      updateTime: '2020-01-17 05:31',
      avatarBg: 'red',
    },
    {
      key: '3',
      name: '设计文档',
      nameIconSrc: '/demos/table-docs-icon.png',
      size: '34KB',
      status: 'wait',
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
    {
      key: '4',
      name: 'Semi D2C 设计文档可能也有点长所以也会显示 Tooltip',
      nameIconSrc: '/demos/table-docs-icon.png',
      size: '34KB',
      status: 'success',
      owner: '姜琪',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'green',
    },
  ],
  '9': [
    {
      key: '1',
      name: 'Semi Design 设计稿.fig',
      nameIconSrc: '/demos/table-figma-icon.png',
      size: 3,
      owner: '姜鹏志',
      updateTime: '2020-02-02 05:13',
      avatarBg: 'grey',
    },
    {
      key: '2',
      name: 'Semi Design 分享演示文稿',
      nameIconSrc: '/demos/table-docs-icon.png',
      owner: '郝宣',
      updateTime: '2020-01-17 05:31',
      avatarBg: 'red',
    },
    {
      key: '3',
      name: '设计文档 3',
      nameIconSrc: '/demos/table-docs-icon.png',
      size: 1,
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
    {
      key: '4',
      name: '设计文档 4',
      nameIconSrc: '/demos/table-docs-icon.png',
      size: 5,
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
    {
      key: '5',
      name: '设计文档 5',
      nameIconSrc: '/demos/table-docs-icon.png',
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
    {
      key: '6',
      name: '设计文档 6',
      nameIconSrc: '/demos/table-docs-icon.png',
      size: 2,
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
  ],
  '14': [
    {
      key: '1',
      name: 'Semi Design 设计稿.fig',
      nameIconSrc: '/demos/table-figma-icon.png',
      size: '2M',
      owner: '姜鹏志',
      updateTime: '2020-02-02 05:13',
      avatarBg: 'grey',
    },
    {
      key: '2',
      name: 'Semi Design 分享演示文稿',
      nameIconSrc: '/demos/table-docs-icon.png',
      size: '2M',
      owner: '郝宣',
      updateTime: '2020-01-17 05:31',
      avatarBg: 'red',
    },
    {
      key: '3',
      name: '设计文档',
      nameIconSrc: '/demos/table-docs-icon.png',
      size: '34KB',
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
  ],
  '15': [
    {
      key: '1',
      name: 'Semi Design 设计稿.fig',
      nameIconSrc: '/demos/table-figma-icon.png',
      size: '2M',
      owner: '姜鹏志',
      updateTime: '2020-02-02 05:13',
      avatarBg: 'grey',
    },
    {
      key: '2',
      name: 'Semi Design 分享演示文稿',
      nameIconSrc: '/demos/table-docs-icon.png',
      size: '2M',
      owner: '郝宣',
      updateTime: '2020-01-17 05:31',
      avatarBg: 'red',
    },
    {
      key: '3',
      name: '设计文档',
      nameIconSrc: '/demos/table-docs-icon.png',
      size: '34KB',
      owner: 'Zoey Edwards',
      updateTime: '2020-01-26 11:01',
      avatarBg: 'light-blue',
    },
  ],
};
