// Generated by scripts/generate-locales.mjs from the read-only v2.102.0 submodule.
// Locale content stays in vendor; the public build selects and inlines these re-exports.
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_ar } from '../../../vendor/semi-design/packages/semi-ui/locale/source/ar.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_az } from '../../../vendor/semi-design/packages/semi-ui/locale/source/az.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_bg } from '../../../vendor/semi-design/packages/semi-ui/locale/source/bg.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_bn_IN } from '../../../vendor/semi-design/packages/semi-ui/locale/source/bn_IN.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_ca } from '../../../vendor/semi-design/packages/semi-ui/locale/source/ca.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_ceb_PH } from '../../../vendor/semi-design/packages/semi-ui/locale/source/ceb_PH.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_cs_CZ } from '../../../vendor/semi-design/packages/semi-ui/locale/source/cs_CZ.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_da } from '../../../vendor/semi-design/packages/semi-ui/locale/source/da.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_de } from '../../../vendor/semi-design/packages/semi-ui/locale/source/de.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_el_GR } from '../../../vendor/semi-design/packages/semi-ui/locale/source/el_GR.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_en_GB } from '../../../vendor/semi-design/packages/semi-ui/locale/source/en_GB.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_en_US } from '../../../vendor/semi-design/packages/semi-ui/locale/source/en_US.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_es } from '../../../vendor/semi-design/packages/semi-ui/locale/source/es.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_es_419 } from '../../../vendor/semi-design/packages/semi-ui/locale/source/es_419.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_et } from '../../../vendor/semi-design/packages/semi-ui/locale/source/et.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_fa_IR } from '../../../vendor/semi-design/packages/semi-ui/locale/source/fa_IR.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_fi_FI } from '../../../vendor/semi-design/packages/semi-ui/locale/source/fi_FI.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_fil_PH } from '../../../vendor/semi-design/packages/semi-ui/locale/source/fil_PH.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_fr } from '../../../vendor/semi-design/packages/semi-ui/locale/source/fr.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_fr_CA } from '../../../vendor/semi-design/packages/semi-ui/locale/source/fr_CA.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_ga } from '../../../vendor/semi-design/packages/semi-ui/locale/source/ga.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_he_IL } from '../../../vendor/semi-design/packages/semi-ui/locale/source/he_IL.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_hi_IN } from '../../../vendor/semi-design/packages/semi-ui/locale/source/hi_IN.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_hr } from '../../../vendor/semi-design/packages/semi-ui/locale/source/hr.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_hu_HU } from '../../../vendor/semi-design/packages/semi-ui/locale/source/hu_HU.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_id_ID } from '../../../vendor/semi-design/packages/semi-ui/locale/source/id_ID.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_is } from '../../../vendor/semi-design/packages/semi-ui/locale/source/is.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_it } from '../../../vendor/semi-design/packages/semi-ui/locale/source/it.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_ja_JP } from '../../../vendor/semi-design/packages/semi-ui/locale/source/ja_JP.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_jv_ID } from '../../../vendor/semi-design/packages/semi-ui/locale/source/jv_ID.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_kk } from '../../../vendor/semi-design/packages/semi-ui/locale/source/kk.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_km_KH } from '../../../vendor/semi-design/packages/semi-ui/locale/source/km_KH.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_ko_KR } from '../../../vendor/semi-design/packages/semi-ui/locale/source/ko_KR.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_lt } from '../../../vendor/semi-design/packages/semi-ui/locale/source/lt.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_lv } from '../../../vendor/semi-design/packages/semi-ui/locale/source/lv.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_ms_MY } from '../../../vendor/semi-design/packages/semi-ui/locale/source/ms_MY.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_my_MM } from '../../../vendor/semi-design/packages/semi-ui/locale/source/my_MM.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_nb } from '../../../vendor/semi-design/packages/semi-ui/locale/source/nb.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_nl_NL } from '../../../vendor/semi-design/packages/semi-ui/locale/source/nl_NL.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_pl_PL } from '../../../vendor/semi-design/packages/semi-ui/locale/source/pl_PL.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_pt } from '../../../vendor/semi-design/packages/semi-ui/locale/source/pt.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_pt_BR } from '../../../vendor/semi-design/packages/semi-ui/locale/source/pt_BR.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_ro } from '../../../vendor/semi-design/packages/semi-ui/locale/source/ro.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_ru_RU } from '../../../vendor/semi-design/packages/semi-ui/locale/source/ru_RU.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_sk } from '../../../vendor/semi-design/packages/semi-ui/locale/source/sk.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_sl } from '../../../vendor/semi-design/packages/semi-ui/locale/source/sl.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_sq } from '../../../vendor/semi-design/packages/semi-ui/locale/source/sq.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_sv_SE } from '../../../vendor/semi-design/packages/semi-ui/locale/source/sv_SE.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_sw } from '../../../vendor/semi-design/packages/semi-ui/locale/source/sw.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_th_TH } from '../../../vendor/semi-design/packages/semi-ui/locale/source/th_TH.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_tr_TR } from '../../../vendor/semi-design/packages/semi-ui/locale/source/tr_TR.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_uk_UA } from '../../../vendor/semi-design/packages/semi-ui/locale/source/uk_UA.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_ur } from '../../../vendor/semi-design/packages/semi-ui/locale/source/ur.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_uz } from '../../../vendor/semi-design/packages/semi-ui/locale/source/uz.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_vi_VN } from '../../../vendor/semi-design/packages/semi-ui/locale/source/vi_VN.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_zh_CN } from '../../../vendor/semi-design/packages/semi-ui/locale/source/zh_CN.ts';
// @ts-expect-error -- pinned vendor data is compiled only through this private boundary.
export { default as pinnedLocale_zh_TW } from '../../../vendor/semi-design/packages/semi-ui/locale/source/zh_TW.ts';
